name: Rerun called
on:
  workflow_call:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: sleep 5
        
  job_3:
    runs-on: ubuntu-latest
    needs: [job_1, job_2]
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  job_4:
    runs-on: ubuntu-latest
    needs: [job_3]
    steps:
      - name: Run a one-line script
        run: sleep 5
